### ISSUE TITLE
Replicating results from the paper

### ISSUE THREAD

**Issue by RorryB** [gudovskiy/contextflow#1]
Would you mind posting the command to replicate the results in the table for ContextFlow?  The command:

`python model.py --gpu 0 --dataset smap --coupling trans --action-type train-generalist`

Appears to be the only one in the command list with dataset as smap.  But that seems to be the generalist model both from the "train-generalist" and from the results I get when I run it compared to the results from the table.

**Comment by gudovskiy** [comment]
Hi @RorryB, please use example commands for the ATM dataset by replacing '--dataset atm' with '--dataset smap'. Let me know if you have any issue by replicating results

**Comment by RorryB** [comment]
That worked, thanks!
